# Generated by Django 5.0.5 on 2024-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_tag', models.CharField(max_length=30, verbose_name='Номер метки')),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Серийный номер')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Дата производства')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='Объём')),
                ('empty_weight', models.FloatField(blank=True, null=True, verbose_name='Вес пустого баллона')),
                ('full_weight', models.FloatField(blank=True, null=True, verbose_name='Вес наполненного баллона')),
                ('current_examination_date', models.DateField(blank=True, null=True, verbose_name='Дата освидетельствования')),
                ('next_examination_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего освидетельствования')),
                ('state', models.CharField(blank=True, max_length=1, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Баллон',
                'verbose_name_plural': 'Баллоны',
            },
        ),
    ]
