# Generated by Django 5.0.6 on 2024-10-24 09:18

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип прицепа')),
            ],
            options={
                'verbose_name': 'Тип прицепа',
                'verbose_name_plural': 'Типы прицепов',
            },
        ),
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип грузовика')),
            ],
            options={
                'verbose_name': 'Тип грузовика',
                'verbose_name_plural': 'Типы грузовиков',
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='balloon',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='balloon',
            name='update_update',
        ),
        migrations.AddField(
            model_name='balloon',
            name='diagnostic_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней диагностики'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='working_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Рабочее давление'),
        ),
        migrations.AddField(
            model_name='balloonevent',
            name='diagnostic_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней диагностики'),
        ),
        migrations.AddField(
            model_name='balloonevent',
            name='working_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Рабочее давление'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер метки'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='size',
            field=models.IntegerField(choices=[(5, 5), (12, 12), (27, 27), (50, 50)], default=50, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='balloonevent',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер метки'),
        ),
        migrations.AlterField(
            model_name='balloonevent',
            name='size',
            field=models.IntegerField(choices=[(5, 5), (12, 12), (27, 27), (50, 50)], default=50, verbose_name='Объём'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='balloon',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "filling_station_balloonevent" ("brutto", "creation_date", "current_examination_date", "diagnostic_date", "id", "manufacturer", "netto", "next_examination_date", "nfc_tag", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "serial_number", "size", "status", "user_id", "wall_thickness", "working_pressure") VALUES (NEW."brutto", NEW."creation_date", NEW."current_examination_date", NEW."diagnostic_date", NEW."id", NEW."manufacturer", NEW."netto", NEW."next_examination_date", NEW."nfc_tag", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."serial_number", NEW."size", NEW."status", NEW."user_id", NEW."wall_thickness", NEW."working_pressure"); RETURN NULL;', hash='595671db7fe2a0768e0f6678a184ed5e62814037', operation='INSERT', pgid='pgtrigger_insert_insert_703b2', table='filling_station_balloon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='balloon',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."brutto" IS DISTINCT FROM (NEW."brutto") OR OLD."creation_date" IS DISTINCT FROM (NEW."creation_date") OR OLD."current_examination_date" IS DISTINCT FROM (NEW."current_examination_date") OR OLD."diagnostic_date" IS DISTINCT FROM (NEW."diagnostic_date") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."manufacturer" IS DISTINCT FROM (NEW."manufacturer") OR OLD."netto" IS DISTINCT FROM (NEW."netto") OR OLD."next_examination_date" IS DISTINCT FROM (NEW."next_examination_date") OR OLD."nfc_tag" IS DISTINCT FROM (NEW."nfc_tag") OR OLD."serial_number" IS DISTINCT FROM (NEW."serial_number") OR OLD."size" IS DISTINCT FROM (NEW."size") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."wall_thickness" IS DISTINCT FROM (NEW."wall_thickness") OR OLD."working_pressure" IS DISTINCT FROM (NEW."working_pressure"))', func='INSERT INTO "filling_station_balloonevent" ("brutto", "creation_date", "current_examination_date", "diagnostic_date", "id", "manufacturer", "netto", "next_examination_date", "nfc_tag", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "serial_number", "size", "status", "user_id", "wall_thickness", "working_pressure") VALUES (NEW."brutto", NEW."creation_date", NEW."current_examination_date", NEW."diagnostic_date", NEW."id", NEW."manufacturer", NEW."netto", NEW."next_examination_date", NEW."nfc_tag", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."serial_number", NEW."size", NEW."status", NEW."user_id", NEW."wall_thickness", NEW."working_pressure"); RETURN NULL;', hash='b97d626dfd3d5bc45a5f299f1335c32378d04c85', operation='UPDATE', pgid='pgtrigger_update_update_08342', table='filling_station_balloon', when='AFTER')),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailertype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trucktype', verbose_name='Тип'),
        ),
    ]
