# Generated by Django 5.0.5 on 2024-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballon',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='Состояние'),
        ),
    ]
