# Generated by Django 5.0.6 on 2024-06-11 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0002_alter_ballon_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballon',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ChangeBallonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_status_date', models.DateField(blank=True, null=True, verbose_name='Дата смены статуса')),
                ('change_status_time', models.TimeField(blank=True, null=True, verbose_name='Время смены статуса')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус')),
                ('ballon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filling_station.ballon')),
            ],
        ),
    ]
