# Generated by Django 5.1.4 on 2025-01-17 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0002_trailertype_trucktype_remove_balloon_insert_insert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railwaybatch',
            name='railway_tank_list',
        ),
        migrations.RemoveField(
            model_name='railwaybatch',
            name='ttn',
        ),
        migrations.RemoveField(
            model_name='railwaybatch',
            name='user',
        ),
        migrations.AlterField(
            model_name='ttn',
            name='consignee',
            field=models.CharField(max_length=50, verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='contract',
            field=models.CharField(max_length=50, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='shipper',
            field=models.CharField(max_length=50, verbose_name='Грузоотправитель'),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер считывателя')),
                ('change_date', models.DateField(auto_now=True, verbose_name='Дата изменений')),
                ('change_time', models.TimeField(auto_now=True, verbose_name='Время изменений')),
                ('balloon_list', models.ManyToManyField(blank=True, to='filling_station.balloon', verbose_name='Список баллонов')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Считыватель',
                'verbose_name_plural': 'Считыватели',
                'ordering': ['-change_date', '-change_time'],
            },
        ),
        migrations.DeleteModel(
            name='RailwayTank',
        ),
        migrations.DeleteModel(
            name='RailwayBatch',
        ),
    ]
