# Generated by Django 5.1.4 on 2025-01-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0003_remove_railwaybatch_railway_tank_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='balloon_list',
        ),
        migrations.AddField(
            model_name='reader',
            name='brutto',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес наполненного баллона'),
        ),
        migrations.AddField(
            model_name='reader',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AddField(
            model_name='reader',
            name='filling_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Готов к наполнению'),
        ),
        migrations.AddField(
            model_name='reader',
            name='netto',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес пустого баллона'),
        ),
        migrations.AddField(
            model_name='reader',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер метки'),
        ),
        migrations.AddField(
            model_name='reader',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='reader',
            name='size',
            field=models.IntegerField(choices=[(5, 5), (12, 12), (27, 27), (50, 50)], default=50, verbose_name='Объём'),
        ),
    ]
