# Generated by Django 5.1.4 on 2025-01-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0004_remove_reader_balloon_list_reader_brutto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='creation_date',
        ),
    ]
