# Generated by Django 5.1.4 on 2025-02-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0005_remove_reader_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloon',
            name='change_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменений'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='change_time',
            field=models.TimeField(auto_now=True, verbose_name='Время изменений'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='filling_status',
            field=models.BooleanField(default=False, verbose_name='Готов к наполнению'),
        ),
        migrations.AlterField(
            model_name='balloon',
            name='update_passport_required',
            field=models.BooleanField(default=True, verbose_name='Требуется обновление паспорта'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='filling_status',
            field=models.BooleanField(default=False, verbose_name='Готов к наполнению'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='nfc_tag',
            field=models.CharField(default='-', max_length=30, verbose_name='Номер метки'),
            preserve_default=False,
        ),
    ]
