# Generated by Django 5.0.6 on 2025-03-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0006_alter_balloon_change_date_alter_balloon_change_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_empty', models.BooleanField(default=False, verbose_name='Принят запрос на наполнение баллона')),
                ('post_number', models.IntegerField(verbose_name='Номер поста наполнения')),
                ('empty_weight', models.FloatField(blank=True, null=True, verbose_name='Вес пустого баллона на посту')),
                ('full_weight', models.FloatField(blank=True, null=True, verbose_name='Вес полного баллона на посту')),
                ('nfc_tag', models.CharField(max_length=30, verbose_name='Номер метки')),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Серийный номер')),
                ('size', models.IntegerField(choices=[(5, 5), (12, 12), (27, 27), (50, 50)], default=50, verbose_name='Объём')),
                ('netto', models.FloatField(blank=True, null=True, verbose_name='Вес пустого баллона')),
                ('brutto', models.FloatField(blank=True, null=True, verbose_name='Вес наполненного баллона')),
                ('filling_status', models.BooleanField(default=False, verbose_name='Готов к наполнению')),
                ('change_date', models.DateField(auto_now=True, verbose_name='Дата изменений')),
                ('change_time', models.TimeField(auto_now=True, verbose_name='Время изменений')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусель',
                'ordering': ['-change_date', '-change_time'],
            },
        ),
    ]
