# Generated by Django 5.0.6 on 2025-03-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0007_сarousel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сarousel',
            new_name='Carousel',
        ),
    ]
