# Generated by Django 5.0.6 on 2025-03-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0008_rename_сarousel_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='size',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='nfc_tag',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер метки'),
        ),
    ]
